import { Roboto } from "next/font/google";
import "./globals.css";
import AppProvider from "./components/AppContext"
import Header from "./components/layouts/Header";
import Footer from "./components/layouts/Footer";
const roboto = Roboto({ subsets: ["latin"], weight: ['400','500','700'] });

export const metadata = {
  title: "Easy Scan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="">
          <AppProvider>
          <Header />
          {children}
          <Footer/>
          </AppProvider>
        </main>
        </body>
    </html>
  );
}
